services:

  casas_db:
    image: docker.io/postgis/postgis:17-3.5
    container_name: casas_db
    restart: always
    env_file:
      - casas.env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  casas_redis:
    image: docker.io/redis:8-alpine
    container_name: casas_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - internal

  casas_django:
    image: localhost/casas
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    hostname: casaswebapp
    container_name: casas_django
    restart: always
    volumes:
      - ./data:/opt/casas/
      - ./grassdata:/opt/grassdata
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - casas_db
      - casas_redis
    env_file:
      - casas.env
    networks:
      - internal
      - default
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${APP_URL}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}


volumes:
  db_data:
  redis_data:

networks:
  default:
    external: true
    name: nginx-proxy-net
  internal:
    driver: bridge
  external:
    name: nginx-proxy-net
